import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./style.css";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const cairo = Cairo({
  weight: ["400", "700"],
  variable: "--font-geist-sans",
  subsets: ["arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${cairo.className} antialiased `}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
